#robot configuration 

driver = "chris"

color = "gold"

hex_primary = 0xC69214
hex_secondary = 0x2a2b2c
hex_tertiary = 0x154734
hex_blue = 0x4EACEC
hex_red = 0xe63242


[pneumatics]
[pneumatics.lowerGate]
    port = 22
    pin = 'h'
[pneumatics.matchLoad]
    port = 22
    pin = 'g'


[encoders]
[encoders.test]
    port = 22
    pin = 'a'



[motorGroups]
    [motorGroups.leftDrive]
        [motorGroups.leftDrive.L1] 
            port = 20
            rev = false
        [motorGroups.leftDrive.L2]
            port = 19
            rev = true
        [motorGroups.leftDrive.L3]
            port = 18
            rev = false
        [motorGroups.leftDrive.L4]
            port = 17
            rev = true
    [motorGroups.rightDrive]
        [motorGroups.rightDrive.R1]
            port = 16
            rev = false
        [motorGroups.rightDrive.R2]
            port = 15
            rev = true
        [motorGroups.rightDrive.R3]
            port = 14
            rev = false
        [motorGroups.rightDrive.R4]
            port = 13
            rev = true

    [motorGroups.conveyor]
        port = 11
        rev = false


[opticals]
    [opticals.frontOpti]
        port = 8


[distances]
    [distances.leftDist]
        port = 2



[chassis]
    drive_setup = "ZERO_TRACKER_ODOM"
    gear_input = 1
    gear_output = 4.5
    wheel_diameter = 3.75
[chassis.encoders]
[chassis.encoders.sideways]
    port = 22
    pin = "a"
    diameter = 2.04
    center_dist = 3.0
[chassis.encoders.forward]
    port = 22
    pin = "c"
    diameter = 2.04
    center_dist = 3.0
[chassis.drivetrain]
    left = "leftDrive"
    right = "rightDrive"
[chassis.inertial]
    port = 21
