#robot port configuration 

color = "gold"

hex_primary = 0xC69214
hex_secondary = 0x2a2b2c
hex_tertiary = 0x154734
hex_blue = 0x4EACEC
hex_red = 0xe63242


[pneumatics]
[pneumatics.lowerGate]
    port = 22
    pin = 'h'
[pneumatics.matchLoad]
    port = 22
    pin = 'g'


[encoders]
[encoders.hori]
    port = 22
    pin = 'a'
[encoders.vert]
    port = 22
    pin = 'c'


[motorGroups]
    [motorGroups.left]
        [motorGroups.left.L1] 
            port = 20
            rev = false
        [motorGroups.left.L2]
            port = 19
            rev = true
        [motorGroups.left.L3]
            port = 18
            rev = false
        [motorGroups.left.L4]
            port = 17
            rev = true
    [motorGroups.right]
        [motorGroups.right.R1]
            port = 16
            rev = false
        [motorGroups.right.R2]
            port = 15
            rev = true
        [motorGroups.right.R3]
            port = 14
            rev = false
        [motorGroups.right.R4]
            port = 13
            rev = true

    [motorGroups.conveyor]
        port = 11
        rev = false


[opticals]
    [opticals.frontOpti]
        port = 8


[distances]
    [distances.leftDist]
        port = 2