[theme]
    color = "GOLD"
    hex_primary = 0xC69214
    hex_secondary = 0x2a2b2c
    hex_tertiary = 0x154734
    hex_blue = 0x4EACEC
    hex_red = 0xe63242

#######################################

[drivetrain]

[drivetrain.left]
    port_front = 20
    port_middle_front = -19
    port_middle_rear = 18
    port_rear = 17

[drivetrain.right]
    port_front = 20
    port_middle_front = -19
    port_middle_rear = 18
    port_rear = 17

#######################################

[odometry]

[odometry.longitudinal_tracker]
    port = 22
    slot = 'A'
    wheel_diameter = 2
    offset = 0

[odometry.lateral_tracker]
    port = 22
    slot = 'C'
    wheel_diameter = 2
    offset = 0

[odometry.inertial_measurement_unit]
    port = 21
    scale_deg = 360

#######################################

[intake]

[intake.first_stage]
    port = 11

[intake.second_stage]
    port = 12

[intake.pneumatic_match_loader]
    port = 22
    slot = "A"

[intake.optical_sensor]
    port = 8
    brightness_pct = 0
    integration_time_ms = 15
